name: addS3BucketAWS

on: push

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      - name: Generate S3 bucket
        run: |
          aws s3 mb s3://this-should-be-unique-${{ steps.extract_branch.outputs.branch }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

  upload-build:
    runs-on: ubuntu-latest
    needs: ["run-shell-command"]
    steps:
      - run: aws s3 sync build s3://this-should-be-unique-master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: we-west-1
